title: Lion pike
author: Lion pike 
description: 
highlighter: null
permalink: /:title

url: http://blog.iikn.cn/
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
